### ISSUE TITLE
is that finished?

### ISSUE THREAD

**Issue by jjhesk** [faceair/fastsocket#1]
yea, please let me know

**Comment by faceair** [comment]
The code is almost complete, but I don't have documentation and testing. It is not ready for use in production today.

**Comment by faceair** [comment]
The design of this project is not compatible with the golang community, such as no io.Reader & net.Conn interface (it is based on goroutine scheduling), which makes this project not work well.
I may not continue to improve this project in the future.

**Comment by jjhesk** [comment]
i see.
